CREATE TABLE PESSOA_FISICA
(
  CD_PESSOA_FISICA varchar2(10 BYTE) NOT NULL,
  IE_TIPO_PESSOA NUMBER(1, 0) NOT NULL,
  NUM_PESSOA_FISICA VARCHAR2(60 BYTE)NOT NULL,
  DT_NASCIMENTO DATE,
  IE_SEXO VARCHAR2(1 BYTE),
  IE_ESTADO_CIVIL VARCHAR2(2 BYTE),
  MR_CPF VARCHAR2(11 BYTE),
  MR_IDENTIDAE VARCHAR2(15 BYTE),
  MR_TELEFONE_CELULAR VARCHAR2(40 BYTE),
  CD_CARGO NUMBER(10, 0),
  CD_ESTABELECIMENTO NUMBER(4, 0),
  DT_ATUALIZACAO_NREC DATE,
  NUM_USUARIO_NREC VARCHAR2(15 BYTE),
  DS_OBSERVACAO VARCHAR2(2000 BYTE),
  DI_NASC DATE,
 
  CONSTRAINT PESSOA_FISICA PRIMARY KEY (CD_PESSOA_FISICA)ENABLE
);

ALTER TABLE PESSOA_FISICA  
MODIFY (NUM_PESSOA_FISICA VARCHAR2(255 BYTE));

CREATE TABLE TITULO_RECEBER
(
  NR_TITULO NUMBER(10,0) NOT NULL,
  CD_PESSOA_FISICA VARCHAR2(20, BYTE),
  VL_TITULO NUMBER(10, 2) DEFAULT 0 NOT NULL,
  VL_SALDO NUMBER(15, 2) DEFAULT 0 NOT NULL,
  CD_CNPJ NUMBER,
  DT_VENCIMENTO DATE NOT NULL,
  CONSTRAINT TITREC_PESFIS_PK PRIMARY KEY(NR_TITULO)ENABLE
  );
  
ALTER TABLE TITULO_RECEBER
ADD CONSTRAINT TITREC_PESFIS_FK FOREIGN KEY(CD_PESSOA_FISICA)
REFERENCES PESSOA_FISICA(CD_PESSOA_FISICA)ENABLE;

INSERT INTO PESSOA_FISICA (CD_PESSOA_FISICA, IE_TIPO_PESSOA, NUM_PESSOA_FISICA, IE_SEXO, MR_CPF, MR_IDENTIDAE, MR_TELEFONE_CELULAR) 
VALUES ('231', '2', 'MARIA', 'F', '89955234892', '258652887', '99999999999');

ALTER TABLE PESSOA_FISICA RENAME COLUMN NUM_PESSOA_FISICA TO NOME_PESSOA_FISICA

ALTER TABLE PESSOA_FISICA MODIFY (IE_TIPO_PESSOA NULL);

CREATE TABLE FUNCIONARIO
(
  NUM_SEQ_FUNC NUMBER,
  VL_SALARIO NUMBER(10, 2)
); 

INSERT INTO FUNCIONARIO
(NUM_SEQ_FUNC, VL_SALARIO)
VALUES(1, 1800.52);

ALTER TABLE FUNCIONARIO ADD DISSIDIO NUMBER(10,2);

ALTER TABLE FUNCIONARIO MODIFY(DISSIDIO NUMBER(10,2) DEFAULT 10);

DELETE FROM TITULO_RECEBER DT_VENCIMENTO WHERE NR_TITULO = 1010;

ALTER TABLE TITULO_RECEBER MODIFY(DT_VENCIMENTO VARCHAR2(255));

UPDATE PESSOA_FISICA SET DT_NASCIMENTO = TO_DATE('21/11/2012', 'DD/MM/YYYY') WHERE CD_PESSOA_FISICA = '231';

ALTER TABLE TITULO_RECEBER DROP COLUMN DT_VENCIMENTO;

ALTER TABLE TITULO_RECEBER ADD DT_VENCIMENTO DATE;

ALTER TABLE TITULO_PAGAR 
ADD CONSTRAINT TITPG_PK PRIMARY KEY(NR_TITULO);

CREATE TABLE FORNECEDOR 
(
  CD_CNPJ VARCHAR2(20) NOT NULL 
, CD_RAZAO_SOCIAL VARCHAR2(100) NOT NULL 
, NOME_CONTATO VARCHAR2(100) 
, CONSTRAINT FORNECEDOR_PK PRIMARY KEY 
  (
    CD_CNPJ 
  )
  ENABLE 
);

CREATE TABLE PESSOA_JURIDICA 
(
  CD_CNPJ VARCHAR2(20 BYTE) NOT NULL,
  DS_RAZAO_SOCIAL VARCHAR2(255 BYTE) NOT NULL, 
  CONSTRAINT PESSOA_JURIDICA_PK PRIMARY KEY (CD_CNPJ) 
  );
  
CREATE TABLE PEDIDOS 
(
  NR_PEDIDO NUMBER NOT NULL 
, CD_CNPJ VARCHAR2(20 BYTE) NOT NULL 
, DT_ORDEM_COMPRA DATE 
, CD_COMPRADOR NUMBER(20, 0) 
, CD_PESSOA_SOLICITANTE NUMBER(20, 0) 
, CD_LOCAL_ENTREGA NUMBER(20, 0) 
, CONSTRAINT PEDIDOS_PK PRIMARY KEY 
  (NR_PEDIDO) 
 );

 ALTER TABLE PEDIDOS ADD CONSTRAINT PESSOA_JURIDICA_FK FOREIGN KEY(CD_CNPJ) REFERENCES PESSOA_JURIDICA(CD_CNPJ);



 
 